### ISSUE TITLE
System status shows different DB versions

### ISSUE THREAD

**Issue by blang9238** [anchore/anchore-cli#106]
`anchore-cli system status` prints different versions for the DB version:

```
[deployment1:~] [anchore-cli] $ anchore-cli system status | tail -3
Engine DB Version: 0.0.13
Engine Code Version: 2.3.1

[deployment2:~] [anchore-cli] $ anchore-cli system status | tail -3
Engine DB Version: 0.0.4
Engine Code Version: 2.3.1
```

Explanation on what's happening from @nurmi :

The reason its changing is that there is only one 'version' displayed, but the order in which the service info comes back from engine is not stable (so the first one in the list is the one that gets displayed).  There isn't anything functionally wrong there, its a reporting issue.  The CLI code had a fix a while back to handle this for the  'code version' output, but wasn't prepared for there to be different 'db version' values for enterprise deployments, so it's non-deterministic what gets displayed at the moment.

**Comment by nightfurys** [comment]
https://github.com/anchore/anchore-cli/issues/89 and https://github.com/anchore/anchore-cli/pull/118 address this issue. Closing this ticket
