### ISSUE TITLE
No module named policy

### ISSUE THREAD

**Issue by tellmejeff** [anchore/anchore-cli#13]
Trying to install the latest anchore-cli. I did the git clone:

> git clone https://github.com/anchore/anchore-cli

And then the pip install:

> pip install --user --upgrade .

And then when I ran it, I got:

> $ anchore-cli
> Traceback (most recent call last):
>   File "/home/osninja/.local/bin/anchore-cli", line 7, in <module>
>     from anchorecli.cli import main_entry
>   File "/home/osninja/.local/lib/python3.5/site-packages/anchorecli/cli/__init__                                                                                       .py", line 7, in <module>
>     import image, policy, evaluate, subscription, registry, system, utils, repo
> ImportError: No module named 'image'

I resolved that by doing:

> pip install image

But now when I run it, I get:

> $ anchore-cli
> Traceback (most recent call last):
>   File "/usr/local/bin/anchore-cli", line 9, in <module>
>     load_entry_point('anchorecli==0.2.0', 'console_scripts', 'anchore-cli')()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
>     return self.resolve()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python3.5/dist-packages/anchorecli/cli/__init__.py", line 7, in <module>
>     import image, policy, evaluate, subscription, registry, system, utils, repo
> ImportError: No module named 'policy'

And I'm not sure what module it is talking about. I also tried:

> pip install -r requirements.txt

But this did not help. Let me know what else I can tell you.

python version 3.5.2
pip version 10.0.1

**Comment by zhill** [comment]
Hi @tellmejeff, thanks for reaching out and thanks for trying anchore! After some quick testing it looks like this is a difference in the import system between python2 and python3. Anchore CLI is a python2 project, at least for now. We're looking at adding python 3 support in the future but aren't quite there yet. Can you retry using python 2.7 and see if that works?

**Comment by tellmejeff** [comment]
Yes, I seem to recall that now. I will give that a whirl.

**Comment by tellmejeff** [comment]
I'm all good. closing.
