### ISSUE TITLE
"anchore-cli system wait" endlessly waiting for disabled feeds to sync

### ISSUE THREAD

**Issue by SimonDreher** [anchore/anchore-cli#138]
We currently have the problem, that our scan pipeline is hanging, because it is stuck on waiting:

    $ anchore-cli system wait      
    Starting checks to wait for anchore-engine to be available timeout=-1.0 interval=5.0
    API availability: Checking anchore-engine URL (http://anchore-engine-anchore-engine- 
    api.anchore.svc.cluster.local:8228/v1/)...
    API availability: Success.
    Service availability: Checking for service set (catalog,apiext,policy_engine,simplequeue,analyzer)...
    Service availability: Success.
    Feed sync: Checking sync completion for feed set (vulnerabilities)...
    Feed sync: Checking sync completion for feed set (vulnerabilities)...
    Feed sync: Checking sync completion for feed set (vulnerabilities)...
    [and so on ...]

Running with debug ouput shows:

    ...
    DEBUG:anchorecli.cli.system:response shows group name=ubuntu:14.10 was last_sync=2020-12- 15T14:00:02.497251
    DEBUG:anchorecli.cli.system:response shows group name=centos:5 was last_sync=None
    DEBUG:anchorecli.cli.system:response shows feed name=nvdv2 was last_full_sync=2020-12-15T14:00:52.906874
    DEBUG:anchorecli.cli.system:response shows feed name=github was last_full_sync=2020-12-15T14:00:56.900292
    DEBUG:anchorecli.cli.system:some feeds not yet synced {'vulnerabilities': False}

The centos feeds were disabled:

    $ anchore-cli system feeds list  
    Feed                   Group                     LastSync                          RecordCount    
    ...
    vulnerabilities        amzn:2                    2020-12-15T14:00:18.990919        510                
    vulnerabilities        centos:5(disabled)        -                                 0                  
    vulnerabilities        centos:6(disabled)        -                                 0                  
    vulnerabilities        centos:7(disabled)        -                                 0                  
    vulnerabilities        centos:8(disabled)        -                                 0                  
    vulnerabilities        debian:10                 2020-12-15T14:00:14.715920        24048              
    vulnerabilities        debian:11                 2020-12-15T14:00:21.483493        21322 
    ...

I suspect that this corner case was not thought of in https://github.com/anchore/anchore-cli/pull/116

After enabling the feeds and triggering a sync, "anchore-cli system wait" finishes quickly.

**Comment by zhill** [comment]
Yes, that looks like an issue. We'll take look. As a workaround I think you should be able to delete the feed group to remove it from the list altogether and that should unblock your script. `anchore-cli system feeds delete vulnerabilities --group centos:5`. Let me know if that works. We'll look into this fix as well, but a bit too late for the 0.9.0 release, so will have to go into 0.9.1 I suspect.

**Comment by SimonDreher** [comment]
As said: after enabling (`anchore-cli system feeds config vulnerabilities --group centos:5 --enable`) and syncing, `anchore-cli system wait` was already unblocked.

Now also disabled `centos:5` again and `anchore-cli system wait` still returned promptly.

After deleting `centos:5`, it still showed up as disable in the feeds list

    vulnerabilities        centos:5(disabled)        -                                 0  

and`anchore-cli system wait` was stuck again.

Just enabling the feed works for us, so we are in no hurry for a fix.
