### ISSUE TITLE
Blocking scan

### ISSUE THREAD

**Issue by Elexy** [anchore/anchore-cli#14]
Apparently the anchore-engine does not currently have a synchronous API for end-to-end image scanning resulting in a policy evaluation output.

The anchore-cli should be able to submit an image and the poll the api, report the status and result when the scan is finished.

I build a little bash script that wraps the anchore-cli to illustrate what I mean.
```
#!/bin/bash

IMAGE_TAG=$1
SLEEPTIME=1

get_status () {
  anchore-cli image get $1 | grep -m 1 "Analysis Status:"
}

if [ -z "$IMAGE_TAG" ]; then
  echo "Error: no image:tag specified"
  exit 1
fi

if anchore-cli image get $IMAGE_TAG | grep Error >> /dev/null; then
  echo "Adding $IMAGE_TAG to anchore"
  anchore-cli image add $IMAGE_TAG
else
  echo "Image $IMAGE_TAG already added"
fi


echo $(get_status $IMAGE_TAG)
until get_status $IMAGE_TAG | grep -m 1 "Analysis Status: analyzed"
do
  if get_status $IMAGE_TAG | grep -m 1 "Analysis Status: analysis_failed"; then exit 1; fi
  sleep $SLEEPTIME
  echo -n "."
done

VULNS=$(anchore-cli image vuln $IMAGE_TAG os)
if [ -z "$VULNS" ]; then
  echo "No known vulnerabilities"
  exit 0
else
  echo "$VULNS"
  exit 1
fi
```

**Comment by zhill** [comment]
Thanks! Very much appreciate the script as an example. You'll see updates in this ticket.

**Comment by zhill** [comment]
I think it makes sense to add a 'wait' command on its own rather than as an option for other commands.

Example:
```
anchore-cli image add docker.io/node:latest
anchore-cli image wait docker.io/node:latest
anchore-cli evaluate check docker.io/node:latest
```

**Comment by zhill** [comment]
@Elexy the design mentioned in the previous comment has been implemented and will be in the next release. Does that resolve the issue for you?

**Comment by zhill** [comment]
The image wait functionality was added in 35ea72cd77abf01c2055a05ea9add32c4b2e6e9b. @Elexy if that works for your use case, can we close this issue?

**Comment by zhill** [comment]
Closing this issue since resolved per previous message.
