### ISSUE TITLE
Add new analysis archive rule attributes to cli get and list

### ISSUE THREAD

**Issue by zburstein** [anchore/anchore-cli#161]
Per @zhill  comment here https://github.com/anchore/anchore-cli/pull/158#pullrequestreview-577490999 we will be adding the new analysis-archive attributes to the list and get ouputs:

1. max_images_per_account
2. registry exclude
3. repository exclude
4. tag exclude
5. exclude expiration

**Comment by zhill** [comment]
Closed by #162
