### ISSUE TITLE
Error: sequence item 1: expected string, NoneType found

### ISSUE THREAD

**Issue by Karreg** [anchore/anchore-cli#18]
Hello,

I'm trying to enable notification through webhook, and part of my test is enabling subscription (not sure it's related though, I was not able to find documentation on CLI features and webhooks in engine).

When looking for CLI syntax for subscription, here is the result:

```
anchore-cli subscription activate                                                                                                 
Usage: anchore-cli subscription activate [OPTIONS] SUBSCRIPTION_TYPE
                                         [SUBSCRIPTION_KEY]

Error: Missing argument "subscription_type".
```

So it looks like I'm missing the subscription_type, other parameters are optional (also, I don't know what are the possible values or where I can get them), fine. I get the list of subscriptions:

```
anchore-cli subscription list    
Tag                                    Subscription Type        Active        
docker.io/library/alpine:latest        analysis_update          True          
docker.io/library/alpine:latest        policy_eval              False         
docker.io/library/alpine:latest        tag_update               True          
docker.io/library/alpine:latest        vuln_update              False         

```
So it looks like one of the subscriptions I can add is "vuln_update":

``
anchore-cli subscription activate vuln_update                                                                                     
Error: sequence item 1: expected string, NoneType found
```

Either vuln_update is not a valid value, or the syntax of the command is not correct. Could you help me with this command? I don't see what the issue is here.

Thanks!

**Comment by Karreg** [comment]
I have finally found the documentation, I was looking for it in the github repo for ages :)

So, found it here: https://anchore.freshdesk.com/support/solutions/articles/36000003890-working-with-subscriptions

It looks like the syntax given by the CLI is obsolete...

**Comment by nurmi** [comment]
hi @Karreg -

That error is not very clear for sure, we'll add a better message which indicates that you also need to supply a 'subscription_key' in addition to a 'subscription_type'

e.g.

```
[nurmi@tele ~]$ anchore-cli subscription list | grep docker.io/alpine:latest
docker.io/alpine:latest                                                      analysis_update          True          
docker.io/alpine:latest                                                      policy_eval              False         
docker.io/alpine:latest                                                      tag_update               True          
docker.io/alpine:latest                                                      vuln_update              False         
[nurmi@tele ~]$ anchore-cli subscription activate vuln_update docker.io/alpine:latest
Success
[nurmi@tele ~]$ anchore-cli subscription list | grep docker.io/alpine:latest
docker.io/alpine:latest                                                      analysis_update          True          
docker.io/alpine:latest                                                      policy_eval              False         
docker.io/alpine:latest                                                      tag_update               True          
docker.io/alpine:latest                                                      vuln_update              True          
```

**Comment by nurmi** [comment]
The bug here, I think, is that the anchore-cli is incorrectly allowing the command to run when subscription_key is not supplied - leaving ticket open to track status of that issue!

**Comment by Karreg** [comment]
Thanks for the explanation of what Subscription Key is. It ws not clear to me :)
