### ISSUE TITLE
Images with names ending with 'local' suffix cannot be deleted by name

### ISSUE THREAD

**Issue by vin01** [anchore/anchore-cli#25]
Hi Team!

**Steps to reproduce:**

Step 1. `anchore-cli  image add docker.io/bitrot/bitrot-local:foo`
Step 2. `anchore-cli  image del docker.io/bitrot/bitrot-local:foo`

Step 2 will throw following error:

`Detail: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.`

**More**

Trying to debug this, when I looked further in `utils.py` I found [this line](https://github.com/anchore/anchore-cli/blob/8318f5cf7c5664297492ec81cdf6968b498139dc/anchorecli/cli/utils.py#L955) which seems to be the culprit.
```
patt = re.match(".*(local:.*)", digest)
```

So in this case image name i.e bitrot-local passes the regex check and image, imagedigest value in `delete` function in `images.py` becomes:

```
(u'docker.io/bitrot/bitrot-local:foo', u'docker.io/bitrot/bitrot-local:foo')
```

After removing this regex test for `local` suffix, deletion is successful with following `image` and `imagedigest` values in `images.py`:

```
('here', u'docker.io/bitrot/bitrot-local:foo', u'sha256:5235d70fd8e63f9ebb780793c0929b6f3913ea587ae28c95a5fb80d20cface62')
```

It looks like an unintentoinal check at first glance. Please review. I will be happy to send a PR 

**Note:** Get, Add operations succeed with the regex check as well, it is just the deletoin which fails. Maybe because that is when the digest is used. Deletion with ID works.

**Comment by nurmi** [comment]
thank you for the report @vin01 - we'll need to review that code since there is an internal form that this regex is intended to match (a special registry.com/reponame@local:<hash> format).  That particular aspect hasn't been reviewed in a while and needs some consideration before we put together a solution that accommodates both cases (i.e. solves the issue you've reported, and also is compatible with/deprecates the @local:<hash> form)

we'll update ticket as we make progress on the issue!

In the meantime, a workaround exists where you can delete images by (for example) digest:

```
# anchore-cli image add docker.io/bitrot/bitrot-local:foo
Image Digest: sha256:5235d70fd8e63f9ebb780793c0929b6f3913ea587ae28c95a5fb80d20cface62
Parent Digest: sha256:5235d70fd8e63f9ebb780793c0929b6f3913ea587ae28c95a5fb80d20cface62
Analysis Status: not_analyzed
Image Type: docker
Image ID: 534a911188ac7b8bfaa68494b6ae5489346b2e5a0ce2f4f69fba2aee28166e60
Dockerfile Mode: None
Distro: None
Distro Version: None
Size: None
Architecture: None
Layer Count: None

Full Tag: docker.io/bitrot/bitrot-local:foo

#
...
...

# anchore-cli image get docker.io/bitrot/bitrot-local:foo
Image Digest: sha256:5235d70fd8e63f9ebb780793c0929b6f3913ea587ae28c95a5fb80d20cface62
Parent Digest: sha256:5235d70fd8e63f9ebb780793c0929b6f3913ea587ae28c95a5fb80d20cface62
Analysis Status: analyzed
Image Type: docker
Image ID: 534a911188ac7b8bfaa68494b6ae5489346b2e5a0ce2f4f69fba2aee28166e60
Dockerfile Mode: Guessed
Distro: debian
Distro Version: 9
Size: 22500661
Architecture: amd64
Layer Count: 1

Full Tag: docker.io/bitrot/bitrot-local:foo

# anchore-cli subscription deactivate tag_update docker.io/bitrot/bitrot-local:foo
Success

# anchore-cli subscription deactivate analysis_update docker.io/bitrot/bitrot-local:foo
Success
# anchore-cli image del docker.io/bitrot/bitrot-local@sha256:5235d70fd8e63f9ebb780793c0929b6f3913ea587ae28c95a5fb80d20cface62
Success
```
