### ISSUE TITLE
Outdated libs

### ISSUE THREAD

**Issue by cinterloper** [anchore/anchore-cli#34]
PyYAML==4.2b1
requests==2.20.0

can these be updated?

**Comment by cinterloper** [comment]
error: certifi 2019.9.11 is installed but certifi==2018.10.15 is required by {'anchorecli'}

**Comment by zhill** [comment]
Closing this as we use a newer version of certifi: https://github.com/anchore/anchore-cli/blob/master/requirements.txt#L1
