### ISSUE TITLE
Why are all my accounts Unauthorized？

### ISSUE THREAD

**Issue by 839588378** [anchore/anchore-cli#37]
Thanks all
I have a question,I have been install anchore-cli on ubuntu 18.04.
I couldn't execute any commands and couldn't connect localhost:8228.
Could you give me any picture guides?Thanks
![图片1](https://user-images.githubusercontent.com/23494356/63580550-a641ba80-c5c7-11e9-939d-26f7eb2d6a4d.png)

**Comment by 839588378** [comment]
I think I'm done?

**Comment by 839588378** [comment]
But I have a doubt. Why can't I open the website     http://myserver.example.com:8228/v1

**Comment by zhill** [comment]
those are the correct environment variables to add to make the CLI functional assuming your installation on you host is available at that dns name. If you have installed on the localhost you may want to use 'localhost' instead of 'myserver.example.com' if whatever DNS name you're using is not publically routable

**Comment by 839588378** [comment]
> 这些是正确的环境变量，要使CLI正常运行，假设您的主机上的安装在该dns名称处可用。如果您已在localhost上安装，则可能需要使用“localhost”而不是“myserver.example.com”，如果您使用的任何DNS名称不可公开路由

Thanks,But I cant't open the website http://localhost:8228/v1 yet

**Comment by 839588378** [comment]
![image](https://user-images.githubusercontent.com/23494356/63998359-8106fc00-cb33-11e9-8c12-608668988150.png)
May I ask, is the construction successful？

**Comment by AlekKras** [comment]
@839588378 ,

You got it right. Run `source ~/.profile` in case it's not working for you if what @zhill said didn't help. That should solve the problems.

**Comment by zhill** [comment]
Closing this as stale. Please re-open if needed or file a new issue if the problem isn't resolved.
