### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by y0no** [anchore/anchore-cli#4]
Is it planned to be compatible with Python 3 ?

**Comment by nurmi** [comment]
Porting forward to Python 3 is certainly in anchore-cli (and other anchore project’s) future, though it is not something that is being actively worked on at this moment.  When the effort does begin, we’ll almost surely start with the CLIs!

**Comment by zhill** [comment]
@y0no is this is a blocking problem for you?

**Comment by y0no** [comment]
This is not really blocking for me but I have to downgrade my workspace to python 2 to use anchore-cli. In fact, I just use "from anchorecli.clients import apiexternal" to use it from a python script.

**Comment by peterloron** [comment]
Any update on this? We're pretty much completely on Python3 at this point...

**Comment by zhill** [comment]
@peterloron it is in active development. This is an unstable branch (very unstable and not fully tested...): [python3 branch](https://github.com/anchore/anchore-cli/tree/python3). Right now the plan is to move to py3 off of py2 rather than supporting both versions. No ETA yet, but the current plan is to roll it out in conjunction with the other parts of anchore moving to py3 as well.

**Comment by zhill** [comment]
hi all, the python3 branch has been merged into master, so the currently head of master branch supports python3. I'm going to mark this ticket resolved.

**Comment by agentreno** [comment]
hey guys, pip3 install from source works, but installing with pip3 from pypi doesn't - maybe it needs updating up there or something?

**Comment by nurmi** [comment]
Hi @agentreno - while we've got python 3 ports in place for anchore-engine and anchore-cli, there has not yet been a release of either that is based on python3 (the versions will be anchore-engine 0.3.0 and anchore-cli 0.3.0).  We typically release both projects in lockstep (for major/minor version updates, to keep feature parity), so the python3/pip update to anchore-cli will happen alongside the anchore-engine 0.3.0 release!

**Comment by nurmi** [comment]
closing this ticket as anchore-engine/anchore-cli version >= 0.3.0 has been ported to python3 - anchore-cli works with either python2 or python3 presently
