### ISSUE TITLE
Anchore CLI stuck at "not_analyzing" and other things

### ISSUE THREAD

**Issue by napindc** [anchore/anchore-cli#41]
When I try to `anchore-cli image add ...` it gives me a failure of 

`Error: failed post url=http://engine-catalog:8228/v1/images
HTTP Code: 500
Detail: {'error_codes': []}`

I then do a `docker-compose ps` and I see `aevolume_engine-catalog_1         /docker-entrypoint.sh anch ...   Up (unhealthy)`

I try to fix the above with a `docker-compose up -d` but it just says everything is up to date. 

So I have to restart my computer, then run `docker-compose up -d` again, and it starts everything up. 

I then run the `anchore-cli image add ...` again, but it gets stuck on `Status: not_analyzed
Waiting 5.0 seconds for next retry.` It does this for about 10 minutes, and then it says `Error: Requested image not found in system` ... I'm then stuck back at square 1. 

Anyone know what is wrong here? I'm using `anchore-cli, version 0.4.1`

**Comment by alfredodeza** [comment]
Could you extract the logs from `engine-catalog` ? Do an `exec` in that container first:

```
$ docker exec -u root -ti aevolume_engine-catalog_1 bash
```

And then look into the log file:

```
$ less /var/log/anchore/anchore.log
```

Would be interesting to check what is going on in there if anything.
