### ISSUE TITLE
"As Account = admin" debug output when logging level INFO

### ISSUE THREAD

**Issue by ikogan** [anchore/anchore-cli#49]
Importing the Anchore CLI in Python causes it to output to "As Account = admin" for every call. This seems like debug output and is polluting the logs of our integration. Here's how we're using it:

```python
import os, logging
from anchorecli.clients import apipexternal as anchore

logging.basicConfig()
logger = logging.getLogger("anchore-integration")
logger.setLevel(level='INFO')

anchore_config = {
    "user": os.getenv('ANCHORE_USERNAME'),
    "pass": os.getenv('ANCHORE_PASSWORD'),
    "url": os.getenv('ANCHORE_URL'),
    "as_account": os.getenv('ANCHORE_USERNAME'),
    "ssl_verify": True
}

repos = anchore.get_repo(anchore_config)
...
```

The final line in there outputs `As Account = admin` (we're currently passing the admin username during out testing).

**Comment by alfredodeza** [comment]
The easier workaround would be to set the log level for `anchore-cli` to `WARNING`, but I am guessing you need some of the output at the `INFO` level? 

Regardless, I agree that the `As account...` line is probably a `DEBUG` one since that function is used heavily everywhere.
