### ISSUE TITLE
Enhance Exit Code Granularity 

### ISSUE THREAD

**Issue by kleppy** [anchore/anchore-cli#6]
While an image is undergoing analysis , any subsequent anchore-cli tasks performed against the image will result in an 'http 404' , and the program will exit with status code 1. It would be useful if the status code and error message reflected the actual state of the image from anchore's perspective. Perhaps assigning unique exit codes to each potential state ('pending', 'failed', 'completed') and having stdout reflect those states, would be useful for users leveraging the CLI for automation purposes.

**Comment by alfredodeza** [comment]
@kleppy I think that `completed` is already a zero exit status right? Perhaps 'pending' could be -1, and 'failed' is currently `2`. When the image does not exist, that is currently a `1`

So to recap, it looks like the only change needed would be for the `pending` state to be a `-1`

**Comment by nightfurys** [comment]
Fixed by #66
